---
dependency:
  name: galaxy

driver:
  name: delegated

platforms:
  - name: instance

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          instance:
            ansible_connection: local

verifier:
  name: ansible

scenario:
  test_sequence:
    - converge
    - verify
